version: "3"

services:
  db:
    container_name: subsquid_db
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    # volumes:
      # - ./assets/${CHAIN}/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./data/db:/var/lib/postgresql/data

