export { CollectionEventResolver } from './collectionEvent'
export { WalletResolver } from './walletResolver'
export { EventResolver } from './event'
export { SeriesResolver } from './series'
export { SpotlightResolver } from './spotlight'
export { TokenResolver } from './tokenEntityByOwner'
