export enum Event {
  clearAttribute = 'Uniques.AttributeCleared',
  setAttribute = 'Uniques.AttributeSet',
  burn = 'Uniques.Burned',
  forceCreateClass = 'Uniques.ForceCreated',
  freezeClass = 'Uniques.ClassFrozen',
  clearClassMetadata = 'Uniques.ClassMetadataCleared',
  setClassMetadata = 'Uniques.ClassMetadataSet',
  thawClass = 'Uniques.ClassThawed',
  freezeCollection = 'Uniques.CollectionFrozen',
  setCollectionMaxSupply = 'Uniques.CollectionMaxSupplySet',
  clearCollectionMetadata = 'Uniques.CollectionMetadataCleared',
  setCollectionMetadata = 'Uniques.CollectionMetadataSet',
  thawCollection = 'Uniques.CollectionThawed',
  createCollection = 'Uniques.Created',
  destroyCollection = 'Uniques.Destroyed',
  freeze = 'Uniques.Frozen',
  createItem = 'Uniques.Issued',
  sold = 'Uniques.ItemBought',
  clearPrice = 'Uniques.ItemPriceRemoved',
  setPrice = 'Uniques.ItemPriceSet',
  clearMetadata = 'Uniques.MetadataCleared',
  setMetadata = 'Uniques.MetadataSet',
  changeIssuer = 'Uniques.OwnerChanged',
  changeOwnershipAcceptance = 'Uniques.OwnershipAcceptanceChanged',
  changeTeam = 'Uniques.TeamChanged',
  thaw = 'Uniques.Thawed',
  transfer = 'Uniques.Transferred',
  // placeOffer = 'Marketplace.OfferPlaced',
  // withdrawOffer = 'Marketplace.OfferWithdrawn',
  // acceptOffer = 'Marketplace.OfferAccepted',
  // payRoyalty = 'Marketplace.RoyaltyPaid',
  // addRoyalty = 'Marketplace.RoyaltyAdded',
  // registerAsset = 'AssetRegistry.Registered',
  // updateAsset = 'AssetRegistry.Updated',
  // setAssetMetadata = 'AssetRegistry.MetadataSet',
}

