export enum Event {
  createClass = 'Uniques.Created',
  forceCreateClass = 'Uniques.ForceCreated',
  setClassMetadata = 'Uniques.ClassMetadataSet',
  clearClassMetadata = 'Uniques.ClassMetadataCleared',
  freezeClass = 'Uniques.ClassFrozen',
  thawClass = 'Uniques.ClassThawed',
  changeIssuer = 'Uniques.OwnerChanged',
  createInstance = 'Uniques.Issued',
  transfer = 'Uniques.Transferred',
  burn = 'Uniques.Burned',
  destroy = 'Uniques.Destroyed',
  createCollection = 'Uniques.CollectionCreated',
  createItem = 'Uniques.ItemMinted',
  transferItem = 'Uniques.ItemTransferred',
  burnItem = 'Uniques.ItemBurned',
  destroyCollection = 'Uniques.CollectionDestroyed',
  setPrice = 'Uniques.ItemPriceSet',
  clearPrice = 'Uniques.ItemPriceRemoved',
  sold = 'Uniques.ItemBought',
  // placeOffer = 'Marketplace.OfferPlaced',
  // withdrawOffer = 'Marketplace.OfferWithdrawn',
  // acceptOffer = 'Marketplace.OfferAccepted',
  // payRoyalty = 'Marketplace.RoyaltyPaid',
  // addRoyalty = 'Marketplace.RoyaltyAdded',
  // registerAsset = 'AssetRegistry.Registered',
  // updateAsset = 'AssetRegistry.Updated',
  // setAssetMetadata = 'AssetRegistry.MetadataSet',
}

